# CBOW & Skip-Gram
---
- cbow: Predict the center word from surrounding words
- skip-gram: Predict surrounding words from the center word

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

import urllib.request
import gensim.downloader as api

model = api.load("word2vec-google-news-300")
print("Model loaded successfully")


Model loaded successfully


In [3]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for filename in os.listdir("D:\\New Csv folder\\archive"):

    f = open(os.path.join("D:\\New Csv folder\\archive",filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [4]:
len(story)

145020

In [5]:
story[1]

['the', 'wildlings', 'are', 'dead']

In [6]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2,
    # worker = 4         
)

In [7]:
model.build_vocab(story)

In [8]:
model.train(story,total_examples = model.corpus_count, epochs=5)

(6570272, 8628190)

In [9]:
model.wv.most_similar('cut')

[('tear', 0.7544408440589905),
 ('chop', 0.7150378823280334),
 ('knocked', 0.7103504538536072),
 ('rip', 0.6979754567146301),
 ('put', 0.6896155476570129),
 ('snatched', 0.6736621260643005),
 ('ripped', 0.6708381772041321),
 ('pull', 0.6704941987991333),
 ('set', 0.6628521084785461),
 ('shoved', 0.6580764055252075)]

In [10]:
# model.wv.doesnt_match()
model.wv['king']

array([-0.18416773,  0.9943656 ,  3.63609   ,  0.7152447 , -3.673391  ,
        0.42927405,  1.8183026 ,  1.1781847 , -3.2613654 , -0.26688126,
       -1.0292195 ,  0.27803192, -0.30071908,  2.0636818 , -3.2002358 ,
       -1.4079729 , -0.05460255,  2.8826275 , -0.02010094, -1.0040181 ,
        0.8289403 ,  0.3394913 ,  3.0299501 , -3.1149213 , -3.0558255 ,
        0.6327878 , -1.1429988 , -1.386051  ,  0.567858  ,  0.49144602,
       -1.1985132 ,  1.5420272 ,  0.27181414, -0.09918527,  2.4127996 ,
       -3.6312964 , -1.4498405 , -2.877115  ,  1.144978  , -3.0944066 ,
        0.77769595,  2.5039608 ,  1.3525047 ,  0.47792152, -0.19579667,
       -1.9959877 ,  1.385728  , -2.1315577 ,  3.357576  , -2.920233  ,
       -3.205791  , -0.11136927, -1.2410765 , -2.26978   ,  2.4419825 ,
       -2.0224407 ,  0.9651316 ,  1.5472517 ,  1.2341292 ,  1.8141929 ,
        1.265764  ,  1.044906  ,  0.8227811 ,  1.3564473 ,  0.5208583 ,
        1.12364   ,  0.23684795, -0.7496762 , -0.55201244, -1.32

In [11]:
model.wv.similarity('arya','sansa')

np.float32(0.8342893)

In [12]:
model.wv.similarity('jon','snow')

np.float32(0.5168271)

In [13]:
# model.wv.get_normed_vectors().shape
model.wv.get_normed_vectors()

array([[-0.09505093, -0.09456872,  0.19131643, ..., -0.08724564,
        -0.04283002,  0.15671498],
       [-0.09395572, -0.08693476,  0.07997078, ..., -0.06093964,
         0.02726173,  0.09709584],
       [ 0.08386892, -0.12310979, -0.02313754, ..., -0.03530234,
         0.07567506, -0.07185133],
       ...,
       [ 0.11187654, -0.0205013 , -0.01245612, ..., -0.07209703,
         0.08750267, -0.09495403],
       [-0.04366466,  0.0261181 , -0.00330816, ..., -0.15737675,
         0.00313659, -0.05900615],
       [ 0.02606001,  0.04972674,  0.14064112, ...,  0.00809435,
         0.09754779, -0.05718763]], dtype=float32)

In [14]:
y = model.wv.index_to_key
y[:10]

['the', 'and', 'to', 'of', 'he', 'his', 'was', 'you', 'her', 'in']

In [15]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)

x = pca.fit_transform(model.wv.get_normed_vectors())

In [16]:
x[:5]

array([[ 0.13691916,  0.59075713, -0.06793715],
       [ 0.16047977,  0.3390953 ,  0.01211487],
       [-0.3019809 ,  0.57973915,  0.20034143],
       [ 0.01987258,  0.37774488, -0.14716996],
       [-0.11309245,  0.53826   ,  0.27572042]], dtype=float32)

In [17]:
import plotly.express as px
fig = px.scatter_3d(x[:500],x=0,y=1,z=2,color=y[:500])
fig.show()